

RABBITMQ_URL: localhost
MONGODB_URL: localhost
MONGODB_DBNAME: odex_test
ENABLE_TLS: "false"
SERVER_PORT: 8081

OBYTE_NODE_HTTP_URL: http://localhost:16333
OBYTE_NODE_WS_URL: ws://localhost:16333


logs:
  main: '.logs/main.log'
  engine: '.logs/engine.log'
  operator: '.logs/operator.log'

tick_duration:
    sec: [5, 30]
    min: [1, 5, 15]
    hour: [1]
    day: [1]
    week: [1]
    month: [1, 3, 6, 9]
    year: [1]
